site_name: restless
site_description: an exploration of â˜ï¸ and ğŸ´
repo_url: https://github.com/octaflop/restless
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/octaflop">octaflop</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
